# File path: pubspec.yaml
name: ilibrary_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # تم تحديث نطاق الـ SDK ليتوافق مع أحدث الممارسات

dependencies:
  flutter:
    sdk: flutter
  
  # الحزم التي نستخدمها
  video_player: ^2.8.6
  chewie: ^1.7.5
  just_audio: ^0.9.36
  animated_text_kit: ^4.2.2
  graphql_flutter: ^5.2.0 
  http: ^1.2.0
  provider: ^6.1.2 # تم تحديث النسخة
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # تم تحديث النسخة

flutter:
  uses-material-design: true

  # --- ✅ هذا هو الجزء الأهم ---
  # تأكد من أن المسافات مطابقة تمامًا
  assets:
    - assets/images/
    - assets/videos/
    - assets/audio/

